#### general settings
name: PAN_deblur
use_tb_logger: True
model: sr_event
distortion: sr_event
scale: 1
save_img: True
gpu_ids: [0]

#### network structures
network_G:
  which_model_G: PAN_deblur
  in_nc: 5
  out_nc: 3
  nf: 10
  unf: 10
  nb: 16
  scale: 1

#### datasets
datasets:
  train:
    name: GOPRO
    mode: LQGT_event
    dataroot_GT: /gdata/caocz/Event_derain/NTU_total/train/GT
    dataroot_LQ: /gdata/caocz/Event_derain/NTU_total/train/input
    dataroot_event: /gdata/caocz/Event_derain/NTU_total/train/mat
    dataroot_event_H5: /gdata/caocz/Event_derain/NTU_total/train/H5/input.h5
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 2
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
    scale: 1
  val:
    name: GOPRO_valid
    mode: LQGT_event
    dataroot_GT: /gdata/caocz/Event_derain/NTU_total/test/GT
    dataroot_LQ: /gdata/caocz/Event_derain/NTU_total/test/input
    dataroot_event: /gdata/caocz/Event_derain/NTU_total/test/mat
    dataroot_event_H5: /gdata/caocz/Event_derain/NTU_total/test/H5/input.h5
    scale: 1
  
#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 7e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 6000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 5000
  save_checkpoint_freq: !!float 5e7